### ISSUE TITLE
Full MVP

### ISSUE THREAD

**Issue by dherman** [volta-cli/volta#150]
These are the remaining items for Notion to be in a full, end-to-end "minimum viable" state.

- [x] #147 auto-shimming
- [x] #148 install package binaries
- [x] #149 shims for package binaries
- [x] #112 support npm
- [x] #154 intercept global installations
- [ ] #157 add tests and test frameworks
- [ ] error quality
- [x] simplify and clean up web page

**Comment by scalvert** [comment]
Support for fish :)

**Comment by dherman** [comment]
@scalvert Definitely important! We've put some of the abstractions in place already, it just needs someone who's passionate about supporting fish to get it over the finish line. ;) I've detailed the steps in #152.

It's not, however, necessary to block releasing our MVP on fish support. The sooner we get this out, the sooner we can solicit feedback, contribution, etc, and speed up our whole process.

**Comment by charlespierce** [comment]
Closing this meta-issue as we had the MVP release with the rename to Volta :+1:
