### ISSUE TITLE
Flesh out the tests and add frameworks

### ISSUE THREAD

**Issue by mikrostew** [volta-cli/volta#157]
We need a good base set of tests to be confident in the quality of our code, and to help when refactoring and making changes:

- [x] unit tests (see #135)
- [x] acceptance tests (in progress - #142)
- [ ] interface tests - unit tests for things that download/read/etc. using Traits
- [x] smoke tests (see #162)

**Comment by chriskrycho** [comment]
@mikrostew should we mark this finished, prioritize hitting that last checkbox, or do something else with it? 😅
