### ISSUE TITLE
Clean up directory layout

### ISSUE THREAD

**Issue by dherman** [volta-cli/volta#179]
We should clean up the directory layout with a few goals in mind:

- User-modified files are separated from automatically managed files.
- Per-user configuration is separated from site-wide (e.g. company-wide) configuration (like hooks).
- The root of the `~/.notion` directory isn't cluttered with internal Notion files.
- The directory layout is tagged with a `schema` file that explicitly identifies a layout version number, to make future migrations easier.
- The toolchain is organized according to clearly-named concepts corresponding to the (to-be-documented) "plumbing" layers of Notion.

```
.
├── bin
│   ├── node
│   ├── npm
│   ├── npx
│   └── yarn
├── config.toml
├── exe
│   ├── shim
│   └── notion
├── hooks
├── schema
├── shell
│   ├── bash
│   ├── fish
│   ├── tcsh
│   └── zsh
└── tools
    ├── inventory
    │   ├── node
    │   ├── packages
    │   └── yarn
    ├── staging
    │   ├── node
    │   ├── packages
    │   └── yarn
    └── user
        ├── bins
        ├── installed
        └── platform.toml
```

Depends on:

- [ ] #148 Install package binaries
- [ ] #177 Create a `shell` subdirectory
- [ ] #178 Create a `hooks` subdirectory
