### ISSUE TITLE
Implement Updates RFC

### ISSUE THREAD

**Issue by charlespierce** [volta-cli/volta#568]
Tracking the various steps needed to fully implement the updates RFC: https://github.com/volta-cli/rfcs/pull/37

- [ ] #562: Remove activate and deactivate
- [ ] #563: Support binaries on the PATH
- [ ] #564: Create `volta setup`
- [ ] #565: Redo installers
- [ ] #566: Create `volta-migration`
- [ ] #567: Implement Automatic Updates
